name: 0opence

dependencies:
  - av=8.0.3
  - bazel=5.1.1
  - boost_mp11=1.76.0
  - cli11=2.2.0
  - cpp-filesystem=1.5.8
  - cudatoolkit=11.4.4
  - cudatoolkit-dev=11.4.4
  - cudnn=8.3.0
  - dali=1.16.1
  - dm-tree=0.1.5
  - grpc=1.41.0
  - gtest=1.10.0
  - horovod=0.25.0
  - huggingface_hub=0.6.0
  - jpeg-turbo=2.1.0
  - keras=2.9.0
  - langcodes=3.3.0
  - libdate=3.0.1
  - libflac=1.3.3
  - libiconv=1.16
  - libsndfile=1.0.31
  - libsolv=0.7.19
  - lightgbm=3.3.2
  - magma=2.6.1
  - mamba=0.25.1
  - nccl=2.12.7
  - nlohmann_json=3.10.5
  - numactl=2.0.12
  - onnx-runtime=1.12.1
  - onnx=1.12
  - onnxconverter-common=1.9.0
  - onnxmltools=1.11.1
  - openblas=0.3.20
  - opencv=4.6.0
  - openmpi=4.1.1
  - optional-lite=3.4.0
  - orc=1.7.4
  - pyarrow=8.0.0
  - pybind11-abi=4
  - pyDeprecate=0.3.2
  - pyTorch-lightning-bolts=0.5.0
  - pytorch-lightning=1.6.5
  - pytorch_geometric=2.1.0
  - pytorch_scatter=2.0.8
  - pytorch_sparse=0.6.10
  - pytorch=1.10.2
  - pytorch=1.12.1
  - ray_all=1.13.1
  - ray-tune=1.13.1
  - reproc=14.2.3
  - sacremoses=0.0.53
  - safeint=3.0.26
  - sentencepiece=0.1.96
  - skl2onnx=1.12.0
  - spacy=3.3.1
  - spacy-legacy=3.0.9
  - spacy-loggers=1.0.2
  - spdlog=1.9.2
  - tensorboard-data-server=0.6.1
  - tensorboard=2.9.1
  - tensorflow-addons=0.17.0
  - tensorflow-datasets=4.6.0
  - tensorflow-estimators=2.9.0
  - tensorflow-hub=0.12.0
  - tensorflow-io-gcs-filesystem=0.26.0
  - tensorflow-metadata=1.8.0
  - tensorflow-model-optimizations=0.7.3
  - tensorflow-probability=0.17.0
  - tensorflow-text=2.9.0
  - tensorflow-base=2.9.2
  - tf2onnx=1.11.1
  - tokenizers=0.11.4
  - torchtext-base=0.11.2
  - torchtext-base=0.13.1
  - torchvision-base=0.11.3
  - torchvision-base=0.11.3
  - transformers=4.19.2
  - typeguard=2.12.0
  - uwsgi=2.0.20
  - xgboost=1.6.2
  - yaml-cpp=0.6.3
